post:
  summary: Generate an explanation for neuron/feature behavior using the default explainer
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          description: Request model for generating explanations of neuron/feature behavior
          required:
            - activations
            - openrouter_key
            - model
          properties:
            activations:
              type: array
              items:
                $ref: "../../../shared.yaml#/components/schemas/NPActivation"
              description: List of activation records to analyze
            openrouter_key:
              type: string
              description: API key for OpenRouter service
              example: "sk-or-v1-..."
            model:
              type: string
              description: Model identifier to use for explanation generation
              example: "openai/gpt-4o-mini"
  responses:
    200:
      description: Successful explanation generation
      content:
        application/json:
          schema:
            type: object
            required:
              - explanation
            properties:
              explanation:
                type: string
                description: The generated explanation for the given set of activations
    400:
      description: Invalid request
    401:
      $ref: "../../../shared.yaml#/components/responses/UnauthorizedError"
    500:
      description: Server error
