resources:
  - ../base
namePrefix: gpt2-small-public-
commonLabels:
  instance: gpt2-small-public
configMapGenerator:
  - name: inference-config
    literals:
      - MODEL_ID=gpt2-small
      - OVERRIDE_MODEL_ID=gpt2-small
      - DEVICE=cpu
      - MODEL_DTYPE=float32
      - SAE_DTYPE=float32
      - HOST=0.0.0.0
      - TOKEN_LIMIT=400
      - PORT=5002
      - MAX_LOADED_SAES=500
      - SAE_SETS='["res-jb"]'
secretGenerator:
  - name: server-secret
    literals:
      - SECRET=public
