# TODO: ReadWriteOnce doesn't allow rolling updates. So we don't use a persistent volume for now.
#
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: model-storage
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 250Gi
