apiVersion: v1
kind: Service
metadata:
  name: neuronpedia-inference
spec:
  selector:
    app: neuronpedia-inference
    instance: ${INSTANCE_NAME}
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
