# This file provides opt-in volume mounting for the Hugging Face cache directory.
# Use it by setting USE_LOCAL_HF_CACHE=1 when running make commands.
# Example: USE_LOCAL_HF_CACHE=1 make inference-localhost-dev-gpu ...
services:
  inference:
    volumes:
      - ${HOME}/.cache/huggingface/hub:/root/.cache/huggingface/hub
  autointerp:
    volumes:
      - ${HOME}/.cache/huggingface/hub:/root/.cache/huggingface/hub
  graph:
    volumes:
      - ${HOME}/.cache/huggingface/hub:/root/.cache/huggingface/hub

