resources:
  - ../base
namePrefix: llama-31-8b-
commonLabels:
  instance: llama-31-8b
configMapGenerator:
  - name: inference-config
    literals:
      - MODEL_ID=meta-llama/Llama-3.1-8B
      - OVERRIDE_MODEL_ID=meta-llama/Llama-3.1-8B
      - DEVICE=cuda
      - MODEL_DTYPE=bfloat16
      - SAE_DTYPE=bfloat16
      - HOST=0.0.0.0
      - TOKEN_LIMIT=400
      - PORT=5002
      - MAX_LOADED_SAES=500
      - SAE_SETS=["llamascope-res-32k"]
