resources:
  - ../base
namePrefix: gpt2-small-
commonLabels:
  instance: gpt2-small
configMapGenerator:
  - name: inference-config
    literals:
      - MODEL_ID=gpt2-small
      - OVERRIDE_MODEL_ID=gpt2-small
      - DEVICE=cpu
      - MODEL_DTYPE=float32
      - SAE_DTYPE=float32
      - HOST=0.0.0.0
      - TOKEN_LIMIT=400
      - PORT=5002
      - MAX_LOADED_SAES=500
      - SAE_SETS='["att_32k-oai", "res_mid_32k-oai", "mlp_32k-oai", "res_post_32k-oai", "att-kk", "res_fs768-jb", "res_fs1536-jb", "res_fs3072-jb", "res_fs6144-jb", "res_fs12288-jb", "res_fs24576-jb", "res_fs49152-jb", "res_fs98304-jb", "res-jb", "res_sce-ajt", "res_scl-ajt", "res_scefr-ajt", "res_sle-ajt", "res_sll-ajt", "res_slefr-ajt"]'
