openapi: 3.0.0
info:
  title: Neuronpedia - Shared
  description: Shared schema for Neuronpedia
  version: 1.0.0

components:
  responses:
    UnauthorizedError:
      description: X-SECRET-KEY header is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  schemas:
    NPFeature:
      type: object
      description: A feature in Neuronpedia, identified by model, source, and index.
      required:
        - model
        - source
        - index
      properties:
        model:
          type: string
          example: gpt2-small
        source:
          type: string
          example: 0-res-jb
        index:
          type: integer
          example: 14057

    NPActivation:
      type: object
      description: An activation record containing tokens and their corresponding activation values
      required:
        - tokens
        - values
      properties:
        tokens:
          type: array
          items:
            type: string
          description: List of tokens for this text
          example: ["The", "cat", "sat"]
        values:
          type: array
          items:
            type: number
            format: float
          description: Activation values corresponding to each token
          example: [0.5, 0.8, 0.2]

paths: {}
