name: Webapp - Playwright

defaults:
  run:
    working-directory: ./apps/webapp

on:
  push:
    branches: [main, master]
    paths:
      - "apps/webapp/**"
  pull_request:
    branches: [main, master]
    paths:
      - "apps/webapp/**"

jobs:
  test:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg17

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - run: psql -h localhost -U postgres -c 'CREATE EXTENSION vector'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Set up database
        run: npx prisma db push
        env:
          POSTGRES_PRISMA_URL: "postgres://postgres:postgres@localhost:5432/postgres?pgbouncer=true&connect_timeout=15"
          POSTGRES_URL_NON_POOLING: "postgres://postgres:postgres@localhost:5432/postgres"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build
        env:
          NEXT_PUBLIC_URL: "https://neuronpedia.org"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "88888888888888888888888888888888"
          POSTGRES_PRISMA_URL: "postgres://postgres:postgres@localhost:5432/postgres?pgbouncer=true&connect_timeout=15"
          POSTGRES_URL_NON_POOLING: "postgres://postgres:postgres@localhost:5432/postgres"
        run: npm run build

      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_URL: "https://neuronpedia.org"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "88888888888888888888888888888888"
          POSTGRES_PRISMA_URL: "postgres://postgres:postgres@localhost:5432/postgres?pgbouncer=true&connect_timeout=15"
          POSTGRES_URL_NON_POOLING: "postgres://postgres:postgres@localhost:5432/postgres"
        run: npm run test:playwright

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./apps/webapp/playwright-report/
          retention-days: 30
