services:
    autointerp:
      volumes:
        - ../apps/autointerp:/app/apps/autointerp
      environment:
        - RELOAD=${RELOAD:-0}
      command: >
        sh -c "if [ "$$RELOAD" = "1" ]; then
          python -m uvicorn server:app --host 0.0.0.0 --port 5003 --workers 1 --reload;
        else
          python -m uvicorn server:app --host 0.0.0.0 --port 5003 --workers 1;
        fi"
