openapi: 3.0.0
info:
  title: Neuronpedia - AutoInterp Shared Score
  version: 1.0.0

components:
  schemas:
    NPScoreFuzzDetectionType:
      type: string
      enum: [FUZZ, DETECTION]
      description: Type of scoring method, either fuzz or detection

paths: {}
