resources:
  - ../../../base
namePrefix: cpu-
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: neuronpedia-inference
      spec:
        template:
          spec:
            containers:
            - name: neuronpedia-inference
              image: gcr.io/tokyo-griffin-401620/neuronpedia-inference:cpu
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: "4"
                  memory: "48Gi"
                limits:
                  cpu: "7"
                  memory: "56Gi"
