# k8s/base/deployments/webapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: neuronpedia-webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        - secretRef:
            name: db-credentials
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

# NOTE: The HTTPRoute and AuthorizationPolicy (both declared below) may need to be deployed by your K8S Platform Administrators
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: webapp
#   labels:
#     app: webapp
# spec:
#   hostnames:
#   - neuronpedia.org # TODO change this
#   parentRefs:
#   - group: gateway.networking.k8s.io
#     kind: Gateway
#     name: aip-gateway
#     namespace: kong
#   rules:
#     - backendRefs:
#       - group: ""
#         kind: Service
#         name: webapp
#         port: 3000
#         weight: 1
#       matches:
#       - path:
#           type: PathPrefix
#           value: /
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: webapp
# spec:
#   selector:
#     matchLabels:
#       app: webapp
#   rules:
#   - {}