#!/usr/bin/env bash
# Auto-generated by tools/phase3_full_prepare.py.
# Runs 6 swap conditions sequentially; each one uses all 8 GPUs
# (--parallel --workers 8) to distribute 49 source pairs.
set -e
set -u
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)
cd "$REPO"
source .venv/bin/activate
mkdir -p logs/phase3
RUN_ID=${RUN_ID:-full_50states_phase3_$(date +%Y%m%d_%H%M)}
echo "[phase3-swaps] run_id=$RUN_ID, 6 conditions sequential, 8-GPU per condition"
echo "[phase3-swaps] === starting condition: human_dallas ==="
python scripts/experiments/batch/run_batch_swaps.py \
    --config scripts/experiments/batch/configs/full_swap_human_dallas.yml \
    --parallel --workers 8 --gpus 0,1,2,3,4,5,6,7 \
    --run-id "$RUN_ID" \
    > logs/phase3/swap_human_dallas.log 2>&1
echo "[phase3-swaps] === finished condition: human_dallas ==="
echo "[phase3-swaps] === starting condition: auto_dallas ==="
python scripts/experiments/batch/run_batch_swaps.py \
    --config scripts/experiments/batch/configs/full_swap_auto_dallas.yml \
    --parallel --workers 8 --gpus 0,1,2,3,4,5,6,7 \
    --run-id "$RUN_ID" \
    > logs/phase3/swap_auto_dallas.log 2>&1
echo "[phase3-swaps] === finished condition: auto_dallas ==="
echo "[phase3-swaps] === starting condition: auto_top21_dallas ==="
python scripts/experiments/batch/run_batch_swaps.py \
    --config scripts/experiments/batch/configs/full_swap_auto_top21_dallas.yml \
    --parallel --workers 8 --gpus 0,1,2,3,4,5,6,7 \
    --run-id "$RUN_ID" \
    > logs/phase3/swap_auto_top21_dallas.log 2>&1
echo "[phase3-swaps] === finished condition: auto_top21_dallas ==="
echo "[phase3-swaps] === starting condition: auto_top100_dallas ==="
python scripts/experiments/batch/run_batch_swaps.py \
    --config scripts/experiments/batch/configs/full_swap_auto_top100_dallas.yml \
    --parallel --workers 8 --gpus 0,1,2,3,4,5,6,7 \
    --run-id "$RUN_ID" \
    > logs/phase3/swap_auto_top100_dallas.log 2>&1
echo "[phase3-swaps] === finished condition: auto_top100_dallas ==="
echo "[phase3-swaps] === starting condition: auto_top200_dallas ==="
python scripts/experiments/batch/run_batch_swaps.py \
    --config scripts/experiments/batch/configs/full_swap_auto_top200_dallas.yml \
    --parallel --workers 8 --gpus 0,1,2,3,4,5,6,7 \
    --run-id "$RUN_ID" \
    > logs/phase3/swap_auto_top200_dallas.log 2>&1
echo "[phase3-swaps] === finished condition: auto_top200_dallas ==="
echo "[phase3-swaps] === starting condition: shuffled_labels_dallas ==="
python scripts/experiments/batch/run_batch_swaps.py \
    --config scripts/experiments/batch/configs/full_swap_shuffled_labels_dallas.yml \
    --parallel --workers 8 --gpus 0,1,2,3,4,5,6,7 \
    --run-id "$RUN_ID" \
    > logs/phase3/swap_shuffled_labels_dallas.log 2>&1
echo "[phase3-swaps] === finished condition: shuffled_labels_dallas ==="
echo "[phase3-swaps] all conditions finished"
