#!/usr/bin/env bash
# Auto-generated by tools/phase3_full_prepare.py.
# Launches 8-way parallel graph generation, one shard per GPU.
set -u
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)
cd "$REPO"
source .venv/bin/activate
mkdir -p logs/phase3
echo "[phase3-graphs] launching ${#}-shard parallel graph generation"
CUDA_VISIBLE_DEVICES=0 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard0.yml > logs/phase3/graphs_shard0.log 2>&1 &
PID0=$!
echo "[phase3-graphs] shard 0 -> GPU 0, pid $PID0, log logs/phase3/graphs_shard0.log"
CUDA_VISIBLE_DEVICES=1 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard1.yml > logs/phase3/graphs_shard1.log 2>&1 &
PID1=$!
echo "[phase3-graphs] shard 1 -> GPU 1, pid $PID1, log logs/phase3/graphs_shard1.log"
CUDA_VISIBLE_DEVICES=2 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard2.yml > logs/phase3/graphs_shard2.log 2>&1 &
PID2=$!
echo "[phase3-graphs] shard 2 -> GPU 2, pid $PID2, log logs/phase3/graphs_shard2.log"
CUDA_VISIBLE_DEVICES=3 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard3.yml > logs/phase3/graphs_shard3.log 2>&1 &
PID3=$!
echo "[phase3-graphs] shard 3 -> GPU 3, pid $PID3, log logs/phase3/graphs_shard3.log"
CUDA_VISIBLE_DEVICES=4 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard4.yml > logs/phase3/graphs_shard4.log 2>&1 &
PID4=$!
echo "[phase3-graphs] shard 4 -> GPU 4, pid $PID4, log logs/phase3/graphs_shard4.log"
CUDA_VISIBLE_DEVICES=5 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard5.yml > logs/phase3/graphs_shard5.log 2>&1 &
PID5=$!
echo "[phase3-graphs] shard 5 -> GPU 5, pid $PID5, log logs/phase3/graphs_shard5.log"
CUDA_VISIBLE_DEVICES=6 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard6.yml > logs/phase3/graphs_shard6.log 2>&1 &
PID6=$!
echo "[phase3-graphs] shard 6 -> GPU 6, pid $PID6, log logs/phase3/graphs_shard6.log"
CUDA_VISIBLE_DEVICES=7 nohup python scripts/experiments/batch/run_batch_from_yaml.py --config scripts/experiments/batch/configs/_phase3_shards/phase3_graphs_shard7.yml > logs/phase3/graphs_shard7.log 2>&1 &
PID7=$!
echo "[phase3-graphs] shard 7 -> GPU 7, pid $PID7, log logs/phase3/graphs_shard7.log"
echo "[phase3-graphs] all shards launched, waiting..."
wait $PID0 $PID1 $PID2 $PID3 $PID4 $PID5 $PID6 $PID7
echo "[phase3-graphs] all shards finished"
