#!/usr/bin/env bash
# Auto-generated by tools/phase3_resume_prepare.py.
# Single parent process runs all pending states; the multi-GPU branch
# inside activations_local.py distributes activations across GPUs.
set -e
set -u
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)
cd "$REPO"
source .venv/bin/activate
mkdir -p logs/phase3
LOG=logs/phase3/resume_$(date +%Y%m%d_%H%M).log
echo "[phase3-resume] log: $LOG"
exec python -u scripts/experiments/batch/run_batch_from_yaml.py \
    --config scripts/experiments/batch/configs/_phase3_shards/phase3_resume_all.yml \
    > "$LOG" 2>&1
