"""Phase 3 resume helper.

After the failed 8-shard run we have a mix of fully-done states (graph +
grouping), partial states (graph done, no activations/grouping), and still
missing states. The cleanest way to finish Phase A is a *single* parent
process that runs every step for every not-yet-fully-done state, with
multi-GPU activations driven by the existing ThreadPoolExecutor inside
activations_local.py (which DOES correctly pin one GPU per worker).

This script writes one consolidated YAML
(scripts/experiments/batch/configs/_phase3_shards/phase3_resume_all.yml)
plus a launch wrapper (tools/launch_phase3_resume.sh).

It is idempotent: re-run any time. force=false in the YAML means already
generated graph.json files are re-used (no extra Neuronpedia calls).
"""
from __future__ import annotations

from pathlib import Path
from typing import List

import yaml

REPO = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO / "scripts" / "experiments" / "batch" / "configs"
SHARD_DIR = CONFIG_DIR / "_phase3_shards"
FACT_BATCH = REPO / "output" / "usa_states_fact_batch"
MASTER_GRAPH_CONFIG = CONFIG_DIR / "usa_states_fact_full.yml"

OUT_YAML = SHARD_DIR / "phase3_resume_all.yml"
OUT_SH = REPO / "tools" / "launch_phase3_resume.sh"

DEFAULT_GPUS = [0, 1, 2, 3, 4, 5, 6, 7]


def fully_done(slug: str) -> bool:
    p = FACT_BATCH / slug
    return (p / "00 Graph Generation" / "graph.json").exists() and \
           (p / "02 Node Grouping" / "node_grouping.csv").exists()


def main() -> None:
    print("== Phase 3 resume prep ==")
    SHARD_DIR.mkdir(parents=True, exist_ok=True)

    with open(MASTER_GRAPH_CONFIG) as fh:
        master = yaml.safe_load(fh)

    all_items: List[dict] = master["graph_generation"]["templated"]["entities"]["items"]
    pending = [it for it in all_items if not fully_done(it["slug"])]
    done = [it for it in all_items if fully_done(it["slug"])]

    print(f"  total entities:   {len(all_items)}")
    print(f"  fully done:       {len(done)}")
    print(f"  pending (resume): {len(pending)}")
    for it in pending[:6]:
        print(f"    - {it['slug']}")
    if len(pending) > 6:
        print(f"    ... +{len(pending) - 6} more")

    cfg = yaml.safe_load(yaml.safe_dump(master))
    cfg["experiment_name"] = "phase3_resume_all"
    cfg["graph_generation"]["templated"]["entities"]["items"] = pending
    cfg.setdefault("get_activations", {}).setdefault("local", {})["gpus"] = DEFAULT_GPUS
    # Make absolutely sure force=false so we DO NOT re-call Neuronpedia
    # for partial states (their graph.json already exists).
    cfg.setdefault("steps", {})["force"] = False

    with open(OUT_YAML, "w") as fh:
        yaml.safe_dump(cfg, fh, sort_keys=False)
    print(f"\n  wrote {OUT_YAML}")

    sh = [
        "#!/usr/bin/env bash",
        "# Auto-generated by tools/phase3_resume_prepare.py.",
        "# Single parent process runs all pending states; the multi-GPU branch",
        "# inside activations_local.py distributes activations across GPUs.",
        "set -e",
        "set -u",
        "REPO=$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\"/.. && pwd)",
        "cd \"$REPO\"",
        "source .venv/bin/activate",
        "mkdir -p logs/phase3",
        f'LOG=logs/phase3/resume_$(date +%Y%m%d_%H%M).log',
        f'echo "[phase3-resume] log: $LOG"',
        f'exec python -u scripts/experiments/batch/run_batch_from_yaml.py \\',
        f'    --config {OUT_YAML.relative_to(REPO)} \\',
        f'    > "$LOG" 2>&1',
    ]
    OUT_SH.write_text("\n".join(sh) + "\n")
    OUT_SH.chmod(0o755)
    print(f"  wrote {OUT_SH}")

    print("\nNext step:")
    print("  nohup bash tools/launch_phase3_resume.sh > logs/phase3/_resume_master.log 2>&1 &")


if __name__ == "__main__":
    main()
