resources:
  - ../../../base
namePrefix: gpu-lite-
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: neuronpedia-inference
      spec:
        template:
          spec:
            nodeSelector:
              cloud.google.com/gke-accelerator: nvidia-l4
            containers:
            - name: neuronpedia-inference
              image: gcr.io/tokyo-griffin-401620/neuronpedia-inference:gpu
              imagePullPolicy: Always
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: "7"
                  memory: "26Gi"
                limits:
                  nvidia.com/gpu: 1
                  cpu: "8"
                  memory: "26Gi"
